package models

// World is a constant type for a world.
type World string

// World constants.
const (
	Aegis        World = "Aegis"
	Atomos       World = "Atomos"
	Carbuncle    World = "Carbuncle"
	Garuda       World = "Garuda"
	Gungnir      World = "Gungnir"
	Kujata       World = "Kujata"
	Ramuh        World = "Ramuh"
	Tonberry     World = "Tonberry"
	Typhon       World = "Typhon"
	Unicorn      World = "Unicorn"
	Alexander    World = "Alexander"
	Bahamut      World = "Bahamut"
	Durandal     World = "Durandal"
	Fenrir       World = "Fenrir"
	Ifrit        World = "Ifrit"
	Ridill       World = "Ridill"
	Tiamat       World = "Tiamat"
	Ultima       World = "Ultima"
	Valefor      World = "Valefor"
	Yojimbo      World = "Yojimbo"
	Zeromus      World = "Zeromus"
	Anima        World = "Anima"
	Asura        World = "Asura"
	Belias       World = "Belias"
	Chocobo      World = "Chocobo"
	Hades        World = "Hades"
	Ixion        World = "Ixion"
	Mandragora   World = "Mandragora"
	Masamune     World = "Masamune"
	Pandaemonium World = "Pandaemonium"
	Shinryu      World = "Shinryu"
	Titan        World = "Titan"
	Adamantoise  World = "Adamantoise"
	Balmung      World = "Balmung"
	Cactuar      World = "Cactuar"
	Coeurl       World = "Coeurl"
	Faerie       World = "Faerie"
	Gilgamesh    World = "Gilgamesh"
	Goblin       World = "Goblin"
	Jenova       World = "Jenova"
	Mateus       World = "Mateus"
	Midgardsormr World = "Midgardsormr"
	Sargatanas   World = "Sargatanas"
	Siren        World = "Siren"
	Zalera       World = "Zalera"
	Behemoth     World = "Behemoth"
	Brynhildr    World = "Brynhildr"
	Diabolos     World = "Diabolos"
	Excalibur    World = "Excalibur"
	Exodus       World = "Exodus"
	Famfrit      World = "Famfrit"
	Hyperion     World = "Hyperion"
	Lamia        World = "Lamia"
	Leviathan    World = "Leviathan"
	Malboro      World = "Malboro"
	Ultros       World = "Ultros"
	Cerberus     World = "Cerberus"
	Lich         World = "Lich"
	Louisoix     World = "Louisoix"
	Moogle       World = "Moogle"
	Odin         World = "Odin"
	Omega        World = "Omega"
	Phoenix      World = "Phoenix"
	Ragnarok     World = "Ragnarok"
	Shiva        World = "Shiva"
	Zodiark      World = "Zodiark"
)
